export const testData = [
  { email: 'user1@example.com', name: 'John Smith' },
  { email: 'user2@example.com', name: 'Emma Wilson' },
  { email: 'user3@example.com', name: 'Michael Brown' },
  { email: 'user4@example.com', name: 'Sarah Davis' },
  { email: 'user5@example.com', name: 'James Miller' },
  { email: 'user6@example.com', name: 'Lisa Anderson' },
  { email: 'user7@example.com', name: 'David Taylor' },
  { email: 'user8@example.com', name: 'Jennifer White' },
  { email: 'user9@example.com', name: 'Robert Martin' },
  { email: 'user10@example.com', name: 'Patricia Moore' },
  { email: 'user11@example.com', name: 'Daniel Lee' },
  { email: 'user12@example.com', name: 'Michelle Clark' },
  { email: 'user13@example.com', name: 'Kevin Wright' },
  { email: 'user14@example.com', name: 'Laura Garcia' },
  { email: 'user15@example.com', name: 'Steven Hall' },
  { email: 'user16@example.com', name: 'Maria Lopez' },
  { email: 'user17@example.com', name: 'Thomas King' },
  { email: 'user18@example.com', name: 'Karen Young' },
  { email: 'user19@example.com', name: 'Joseph Baker' },
];
